language: ruby
rvm:
  - 1.9.3
# env:
  # - AWS_ACCESS_KEY_ID="foo" AWS_SECRET_ACCESS_KEY="bar" ADEPT_S3_BUCKET="baz"
bundler_args: --without local
script: 
  - bundle exec rake spec:ci
before_install:
  - sudo apt-get update -qq
  # - sudo apt-get install -qq libarchive-dev
before_script:
  - createuser -s reveille
  - rake db:create:all
  - rake db:migrate
  - rake db:test:prepare
branches:
  only:
    - master